//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASINO.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonuses
    {
        public int Id { get; set; }
        public string BonusType { get; set; }
        public decimal Amount { get; set; }
        public decimal MinDeposit { get; set; }
        public decimal MaxBonus { get; set; }
    }
}
